import os
import torch
import seisbench.models as sbm
import seisbench.data as sbd
from seisbench.util import worker_seeding
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader

def main():
    # Set paths
    dataset_dir = "/home/rt/rawdata/Korea_dataset/Dataset"
    input_csv = os.path.join(dataset_dir, "metadata_2020.csv")
    input_hdf5 = os.path.join(dataset_dir, "waveforms_2020.hdf5")
    
    # Output directory for the model
    output_dir = "seisbench_model_output"
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Starting SeisBench training process...")
    print(f"Input CSV: {input_csv}")
    print(f"Input HDF5: {input_hdf5}")
    
    # In SeisBench, you typically load datasets directly using its API or convert them
    # For this example, we assume you have custom data and need to wrap it into a SeisBench Dataset.
    # Because your data is custom (Korea Dataset), we will use SeisBench's generic WaveformDataset class.
    # Note: If your HDF5/CSV is not in SeisBench format, you may need to convert it first or use your own custom DataLoader.
    
    try:
        # Load the custom dataset. 
        # (Assumes your dataset is structured in a way SeisBench's WaveformDataset can parse)
        dataset = sbd.WaveformDataset(dataset_dir)
        print("Dataset loaded successfully!")
    except Exception as e:
        print(f"\n[!] Notice: Failed to load dataset directly with SeisBench: {e}")
        print("Your dataset might not be in the standard SeisBench format (SeisBench requires a specific HDF5/CSV layout).")
        print("Please use `seisbench.data.WaveformDataset.write` to convert your dataset, or implement a custom PyTorch Dataset.")
        return

    # Split dataset into train/validation sets using SeisBench API
    # Since dataset is loaded as a WaveformDataset, we should use its train/dev split.
    try:
        train_dataset = dataset.train()
        val_dataset = dataset.dev()
        # If train/dev splits are not pre-defined in the metadata, we split manually via generator
        if len(train_dataset) == 0:
            print("No predefined train/dev split found, using 80/20 split via metadata.")
            dataset.metadata['split'] = ['train' if i < int(0.8*len(dataset)) else 'dev' for i in range(len(dataset))]
            train_dataset = dataset.train()
            val_dataset = dataset.dev()
    except Exception as e:
        print(f"Error handling splits: {e}")
        return

    import numpy as np
    import seisbench.generate as sbg
    batch_size = 64
    
    # Define augmentations. This provides the necessary keys (X, y, etc.)
    # Window size should match the expected input length of your model (EQTransformer expects 6000 samples)
    phase_dict = {"trace_p_arrival_sample": "P", "trace_s_arrival_sample": "S"}
    
    train_generator = sbg.GenericGenerator(train_dataset)
    train_generator.add_augmentations([
        sbg.WindowAroundSample(list(phase_dict.keys()), samples_before=3000, windowlen=6000, selection="random", strategy="variable"),
        sbg.RandomWindow(windowlen=6000, strategy="pad"),
        sbg.Normalize(demean_axis=-1, amp_norm_axis=-1, amp_norm_type="std"),
        sbg.ChangeDtype(np.float32),
        sbg.ProbabilisticLabeller(label_columns=phase_dict, sigma=20, dim=0)
    ])
    
    train_loader = DataLoader(train_generator, batch_size=batch_size, shuffle=True, worker_init_fn=worker_seeding)

    # Initialize Model
    # Here you can choose: sbm.EQTransformer(), sbm.PhaseNet(), etc.
    model = sbm.EQTransformer(phases="PS") 
    
    # Device setup
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    model.to(device)

    # Loss and Optimizer
    # EQTransformer outputs 3 values (Detection, P-pick, S-pick), so we use a loss function that supports this.
    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    epochs = 10
    
    # Basic Training Loop
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        
        for batch in train_loader:
            # batch is a dictionary generated by SeisBench's generic generator
            waveforms = batch["X"].to(device)
            # targets is typically shape (batch, 3, samples) for noise, P, S
            targets = batch["y"].to(device)
            
            optimizer.zero_grad()
            
            # Forward pass: eqtransformer returns (detection, p_pick, s_pick)
            outputs = model(waveforms)
            
            # Pack outputs into a single tensor to match targets shape for BCEWithLogitsLoss
            # EQTransformer returns 3 tensors of shape (batch, samples)
            if len(outputs) == 3:
                # Stack along dim=1 to get (batch, 3, samples)
                out_stacked = torch.stack(outputs, dim=1)
            else:
                out_stacked = outputs
            
            loss = criterion(out_stacked, targets) 
            
            # Backward pass
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
            
        avg_train_loss = train_loss / len(train_loader)
        print(f"Epoch [{epoch+1}/{epochs}] - Train Loss: {avg_train_loss:.4f}")
        
    # Save the trained model parameters
    model_path = os.path.join(output_dir, "eqtransformer_seisbench_custom.pt")
    torch.save(model.state_grad_dict(), model_path)
    print(f"Training complete. Model saved to: {model_path}")

if __name__ == "__main__":
    main()
